name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: heliumsystems/builder-erlang:1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v1
        with:
          path: ~/.cache/rebar3/rebar3_*_plt
          key: ${{ runner.os }}-dialyzer-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.config')) }}
          restore-keys: |
            ${{ runner.os }}-dialyzer-

      - name: Test
        run: make test

      - name: Dialyze
        run: make dialyze
